"""change_marketplace_to_string

Revision ID: 7fcee902115d
Revises: 002_add_user_status
Create Date: 2025-12-05 00:39:37.758227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fcee902115d'
down_revision = '002_add_user_status'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_global', 'marketplace',
               existing_type=postgresql.ENUM('chariow', 'maketou', 'systemio', 'systemeio', 'other', name='marketplacetype'),
               type_=sa.Enum('chariow', 'maketou', 'systemio', 'systemeio', 'other', name='marketplacetype', native_enum=False),
               existing_nullable=False)
    op.alter_column('shops_global', 'marketplace',
               existing_type=postgresql.ENUM('chariow', 'maketou', 'systemio', 'systemeio', 'other', name='marketplacetype'),
               type_=sa.Enum('chariow', 'maketou', 'systemio', 'systemeio', 'other', name='marketplacetype', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='userstatus'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::userstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='userstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::userstatus"))
    op.alter_column('shops_global', 'marketplace',
               existing_type=sa.Enum('chariow', 'maketou', 'systemio', 'systemeio', 'other', name='marketplacetype', native_enum=False),
               type_=postgresql.ENUM('chariow', 'maketou', 'systemio', 'systemeio', 'other', name='marketplacetype'),
               existing_nullable=False)
    op.alter_column('products_global', 'marketplace',
               existing_type=sa.Enum('chariow', 'maketou', 'systemio', 'systemeio', 'other', name='marketplacetype', native_enum=False),
               type_=postgresql.ENUM('chariow', 'maketou', 'systemio', 'systemeio', 'other', name='marketplacetype'),
               existing_nullable=False)
    # ### end Alembic commands ###

